name: "Gh Rebot for Sealos"
description: "Add some robot command for sealos"
author: "cuisongliu"
inputs:
  version:
    description: 'version of gh-robot'
    required: true
    default: 'v0.0.5'
runs:
  using: "composite"
  steps:
  - run: |
      sudo wget -q https://github.com/labring/gh-robot/releases/download/${GH_REBOT_VERSION}/gh-robot_${GH_REBOT_VERSION#v}_linux_amd64.tar.gz
      sudo tar -zxf gh-robot_${GH_REBOT_VERSION#v}_linux_amd64.tar.gz gh-robot &&  chmod +x gh-robot && sudo mv gh-robot /usr/bin/gh-robot
      gh-robot version
      sudo rm -rf gh-robot_${GH_REBOT_VERSION#v}_linux_amd64.tar.gz
      gh-robot action
    shell: bash
    env:
      GH_REBOT_VERSION: ${{ inputs.version }}
branding:
  icon: 'user-check'
  color: 'orange'
